---
- name: Get the ubuntu Install disk
  get_url: url=http://releases.ubuntu.com/14.04.3/ubuntu-14.04.3-server-amd64.iso dest=/var/www/html/ubuntu.iso

- name: Add index page
  copy: src=index.html dest=/var/www/html/index.html owner=root group=root mode=0644

