---
- name: Install python selinux
  yum: name=libselinux-python state=present

- name: Install EPEL
  yum: name=epel-release state=present

- name: Install Services
  yum: name={{ item }} state=present
  with_items:
    - unbound
    - nsd
    - dhcp
    - ntp
    - ntpdate

- name: Install iptables
  yum: name=iptables state=present

- name: Add iptables script
  copy: src=iptables dest=/usr/local/bin/iptables owner=root group=root mode=0740

- name: Copy ifup-local file
  copy: src=ifup-local dest=/sbin/ifup-local owner=root group=root mode=0740

- name: Create iptables directory
  file: path=/etc/iptables.d state=directory owner=root group=root mode=0750

- name: Configure IPv4 firewall
  copy: src=cluster.rules dest=/etc/iptables.d/cluster.rules owner=root group=root mode=0640
  notify:
  - iptables

- name: Copy NSD Config
  copy: src=nsd.conf dest=/etc/nsd/nsd.conf owner=root group=root mode=0640 validate='nsd-checkconf %s'
  notify:
    - nsd

- name: Add Master Zones
  copy: src={{ item }} dest=/etc/nsd/{{ item }} owner=root group=root mode=0640
  with_items:
    - cluster.lug.utdallas.edu
    - 42.16.172.in-addr.arpa
  notify:
    - nsd

- name: Copy Unbound Config
  template: src=unbound.conf dest=/etc/unbound/unbound.conf owner=root group=unbound mode=0644 validate='unbound-checkconf /etc/unbound/../../%s'
  notify:
    -unbound

- name: Run NSD Trust Setup
  command: nsd-control-setup

- name: Run Unbound Trust Setup
  command: unbound-control-setup

- name: Enable NSD
  service: name=nsd enabled=yes

- name: Start NSD
  service: name=nsd state=started

- name: Enable Unbound
  service: name=unbound enabled=yes

- name: Start Unbound
  service: name=unbound state=started

- name: Copy DHCP sysconfig
  copy: src=sysconfig-dhcpd dest=/etc/sysconfig/dhcpd owner=root group=root mode=0644

- name: Copy eth1 config
  copy: src=sysconfig-ifcfg-eth1 dest=/etc/sysconfig/network-scripts/ifcfg-eth1 owner=root group=root mode=0644
  register: sysconfigeth1

- name: Copy eth0 config
  copy: src=sysconfig-ifcfg-eth0 dest=/etc/sysconfig/network-scripts/ifcfg-eth0 owner=root group=root mode=0644
  register: sysconfigeth0
  
- name: Restart Network
  command: /etc/init.d/network restart
  when: sysconfigeth1.changed or sysconfigeth0.changed
  
- name: Copy DHCP Config
  template: src=dhcpd.conf dest=/etc/dhcp/dhcpd.conf owner=root group=root mode=0644
  notify:
    - dhcp

- name: Enable DHCP
  service: name=dhcpd enabled=yes

- name: Start DHCP
  service: name=dhcpd state=started

- name: Enable NTP
  service: name=ntpd enabled=yes

- name: Start NTP
  service: name=ntpd state=started
