---
- name: Copy theme
  copy: src=lug dest=/opt/ltsp/i386/usr/share/ldm/themes/lug owner=root group=root mode=0644
  notify: ltsp-image-update

- name: Copy lts.conf
  copy: src=lts.conf dest=/var/lib/tftpboot/ltsp/i386/lts.conf owner=root group=root mode=0644
